---
title: "F1s and F2s to Plant"
author: "Brandie Quarles"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries
```{r}
library(tidyverse)
library(googlesheets4)
url_f1s <- "https://docs.google.com/spreadsheets/d/1t5X39iisjTCknwkyNLs8Q7bmiKYkmkWtPZbpj3Ce4N8/edit#gid=709784644"
url_f2s <- "https://docs.google.com/spreadsheets/d/1bw6rzqCcrGjE5DuIe4oxC_GMPKG66nHHNyT_iY5umBQ/edit#gid=729112464"
```

## Load Data

### F1s
```{r}
F1s <- read_sheet(url_f1s,
                  sheet = "Collected fruits list F1 seed",
                  na=c("NA", "", "unknown")) 
head(F1s)

F1s_short <- F1s %>% select(dame_pop=`dame pop`, dame_mf_rep=`dame mf-rep`, sire_pop=`sire pop`, sire_mf_rep=`sire mf-rep`, date_crossed=`date crossed`, date_collected=`date collected`, seeds_avail=`number of seed updated after fall 2023 planting`, seed_quality=`seed quality`, notes)
head(F1s_short)

F1s_short_summarize <- F1s_short %>% group_by(dame_pop, sire_pop) %>% summarise(Sum_Seeds=sum(seeds_avail))
F1s_short_summarize
dim(F1s_short_summarize) #40 F1 types

F1s_short_summarize_twenty <- F1s_short_summarize %>% filter(Sum_Seeds >= 20) %>% filter(!is.na(sire_pop)) %>% arrange(Sum_Seeds)
F1s_short_summarize_twenty
F1s_short_summarize_twenty %>% filter(Sum_Seeds==20) #13 of the 26 F1s with at least 20 seeds only have 20 seeds 
```

### F2s
```{r}
F2s <- read_sheet(url_f2s,
                  sheet = "Collected fruits F2 seed",
                  #col_types=cols(.default=col_character()), #force all columns to be character
                  na=c("NA", "")) 
head(F2s) #need to make everything a character 

F2s_short <- F2s %>% 
  select(dame_pop=`dame pop/hybrid`, dame_mf_rep=`dame mf-rep/ID`, sire_pop=`sire pop/hybrid`, sire_mf_rep=`sire mf-rep/ID`, date_crossed=`date crossed`, date_collected=`date collected`, emasc_poll=`emasulator-pollinator`, seeds_avail=`number of seed updated after fall 2023 planting`, seed_quality=`seed quality`, notes) %>% 
  filter(!is.na(dame_pop)) %>% 
  mutate(date_collected=ymd(date_collected), Year_Collected=year(date_collected), Year_Collected=ifelse(is.na(Year_Collected), 2023, Year_Collected))
head(F2s_short)

F2s_short_after_ripened <- F2s_short %>% filter(Year_Collected < 2024)

F2s_short_after_ripened_summarize <- F2s_short_after_ripened %>% 
  group_by(dame_pop, sire_pop) %>% 
  summarise(Unique_Crosses=sum(!is.na(seeds_avail)),Sum_Seeds=sum(seeds_avail)) %>% 
  mutate(Seeds_to_Plant=ifelse(Sum_Seeds <= 10, Sum_Seeds, 10)) %>% 
  arrange(Sum_Seeds) 
F2s_short_after_ripened_summarize
dim(F2s_short_after_ripened_summarize) #67 types of F2s
sum(F2s_short_after_ripened_summarize$Sum_Seeds) #1523 total seeds available
sum(F2s_short_after_ripened_summarize$Seeds_to_Plant) #1300 if want 40 seeds/type, 1208 if want 30 seeds/type, 1148 if want 25 seeds/type, 1074 if 20 seeds/type, 616 if 10/type
F2s_short_after_ripened_summarize %>% filter(Sum_Seeds < 20)

F2s_short_after_ripened_summarize_WL2 <- F2s_short_after_ripened_summarize %>% 
  mutate(WL2_mom =str_detect(dame_pop, "WL2"), 
         WL2_dad=str_detect(sire_pop, "WL2"), 
         WL2_cross=ifelse(WL2_mom==TRUE | WL2_dad==TRUE, TRUE, FALSE)) %>% 
  filter(WL2_cross == TRUE)
F2s_short_after_ripened_summarize_WL2
dim(F2s_short_after_ripened_summarize_WL2) #62 types of F2s
sum(F2s_short_after_ripened_summarize_WL2$Sum_Seeds) #1402 total seeds available 
sum(F2s_short_after_ripened_summarize_WL2$Seeds_to_Plant) #1180 if want 40 seeds/type, 1098 if want 30 seeds/type, 1043 if want 25 seeds/type, 974 if 20 seeds/type, 566 if 10/type
F2s_short_after_ripened_summarize_WL2 %>% filter(Sum_Seeds < 20)
```

