---
title: "2025_Seeds_To_Plant"
author: "Brandie QC"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load libraries

```{r}
library(tidyverse)
library(googlesheets4)
url_f1s <- "https://docs.google.com/spreadsheets/d/1t5X39iisjTCknwkyNLs8Q7bmiKYkmkWtPZbpj3Ce4N8/edit#gid=709784644"
url_f2s <- "https://docs.google.com/spreadsheets/d/1bw6rzqCcrGjE5DuIe4oxC_GMPKG66nHHNyT_iY5umBQ/edit#gid=729112464"
url_f1s_2024_update <- "https://docs.google.com/spreadsheets/d/1W9sGeCHn3l0zRb8bdsQPy6QHrEHa2Tb0nnAh_SYz8i8/edit?gid=238525499#gid=238525499"
```

## Load Data

### F1s

```{r}
F1s <- read_sheet(url_f1s,
                  sheet = "Collected fruits list F1 seed",
                  na=c("NA", "", "unknown")) 
head(F1s)

F1s_short <- F1s %>% select(dame_pop=`dame pop`, dame_mf_rep=`dame mf-rep`, sire_pop=`sire pop`, sire_mf_rep=`sire mf-rep`, date_crossed=`date crossed`, date_collected=`date collected`, seeds_avail=`number of seed updated after fall 2023 planting`, seed_quality=`seed quality`, notes)
head(F1s_short)
```

### F1s Update

```{r}
F1s_update <- read_sheet(url_f1s_2024_update,
                  sheet = "Collected fruits F2 seed",
                  na=c("NA", "", "unknown")) %>% 
  filter(str_detect(notes, "F1"))
head(F1s_update)
dim(F1s_update) #102 F1s in this dataframe
summary(F1s_update)
F1s_update %>% filter(!is.na(`...15`))

F1s_update_short <- F1s_update %>% 
  select(dame_pop=`dame pop/hybrid`, dame_mf_rep=`dame mf-rep/ID`, sire_pop=`sire pop/hybrid`, sire_mf_rep=`sire mf-rep/ID`, emasc_poll=`emasulator-pollinator`, date_crossed=`date crossed`, date_collected=`date collected`, seeds_avail_2024=`number of seed updated after spring 2024 planting`, duplicate=`...15`) %>% 
  mutate(date_crossed=ymd(date_crossed),
         date_collected=ymd(date_collected)) 
   
#correct the year (F1s not made after April 2023):
F1s_update_short_2023 <- F1s_update_short %>% filter(date_crossed<"2023-05-01")
F1s_update_short_2022 <- F1s_update_short %>% filter(date_crossed>"2023-05-01") %>%
  mutate(date_crossed=str_replace(date_crossed, "2023", "2022")) %>% 
  mutate(date_collected=str_replace(date_collected, "2023", "2022")) %>% 
  mutate(date_crossed=ymd(date_crossed),
         date_collected=ymd(date_collected))
F1s_update_short_year_corrected <- bind_rows(F1s_update_short_2022, F1s_update_short_2023)

#F1s_update_short_year_corrected %>% filter(!is.na(duplicate)) %>% arrange(dame_pop, dame_mf_rep, sire_pop, sire_mf_rep, date_crossed, date_collected, seeds_avail_2024)
#F1s_update_short_year_corrected %>% arrange(dame_pop, dame_mf_rep, sire_pop, sire_mf_rep, date_crossed, date_collected, seeds_avail_2024)

F1s_update_duplicates_corrected <- F1s_update_short_year_corrected %>% 
  arrange(dame_pop, dame_mf_rep, sire_pop, sire_mf_rep, date_crossed, date_collected, seeds_avail_2024) %>% 
  distinct(dame_pop, dame_mf_rep, sire_pop, sire_mf_rep, date_crossed, date_collected, .keep_all=TRUE)

```

### F1s Merge

```{r}
F1s_all <- full_join(F1s_short, F1s_update_duplicates_corrected) 
#some extra rows --> some in the update doc that are not in the original doc

ISSUES <- F1s_all %>% filter(is.na(seeds_avail)) #2 ROWS, NOT IN OG DOC 

F1s_plant <- F1s_all %>% 
  mutate(seeds_avail_combined=if_else(is.na(seeds_avail_2024), seeds_avail, seeds_avail_2024)) %>% 
  group_by(dame_pop, sire_pop) %>% 
  summarise(Unique_Crosses=sum(!is.na(seeds_avail)), Sum_Seeds=sum(seeds_avail_combined)) %>% 
  arrange(Sum_Seeds) 
#F1s_plant
dim(F1s_plant) #40 types of F1s
sum(F1s_plant$Sum_Seeds) #734 total seeds available

F1s_plant_summarize_WL2 <- F1s_plant %>% 
  mutate(WL2_mom =str_detect(dame_pop, "WL2"), 
         WL2_dad=str_detect(sire_pop, "WL2"), 
         WL2_cross=ifelse(WL2_mom==TRUE | WL2_dad==TRUE, TRUE, FALSE)) %>% 
  filter(WL2_cross == TRUE) %>% 
  filter(Sum_Seeds>0) %>% 
  filter(!is.na(sire_pop)) %>% 
  select(dame_pop:Sum_Seeds, WL2_cross) 
head(F1s_plant_summarize_WL2)
dim(F1s_plant_summarize_WL2) #18 types of F1s with WL2 involved 
sum(F1s_plant_summarize_WL2$Sum_Seeds) #297 WL2 F1 seeds 

F1s_to_plant_2025 <- F1s_plant_summarize_WL2 %>% 
  mutate(BC1_parent=if_else(dame_pop=="TM2" | 
                              dame_pop=="DPR" |
                              dame_pop=="BH" |
                              dame_pop=="WV" |
                              dame_pop=="WL1" |
                              sire_pop=="TM2" | 
                              sire_pop=="DPR" |
                              sire_pop=="BH" |
                              sire_pop=="WV" |
                              sire_pop=="WL1", TRUE, FALSE)) %>% 
  mutate(pots_to_plant_raw = if_else(Sum_Seeds<3, Sum_Seeds, Sum_Seeds/3),
         pots_to_plant_round = round(pots_to_plant_raw),
         seeds_to_plant = Sum_Seeds)
F1s_to_plant_2025
sum(F1s_to_plant_2025$pots_to_plant_round) #97 pots 
```

### F2s

```{r}
F2s <- read_sheet(url_f2s,
                  sheet = "Collected fruits F2 seed",
                  #col_types=cols(.default=col_character()), #force all columns to be character
                  na=c("NA", "")) 
#head(F2s) #need to make everything a character 

F2s_short <- F2s %>% 
  select(dame_pop=`dame pop/hybrid`, dame_mf_rep=`dame mf-rep/ID`, sire_pop=`sire pop/hybrid`,
         sire_mf_rep=`sire mf-rep/ID`, date_crossed=`date crossed`, 
         date_collected=`date collected`, emasc_poll=`emasulator-pollinator`, 
         seeds_avail=`number of seed updated after winter 2024 crossing planting`, 
         seed_quality=`seed quality`, notes) %>% 
  filter(!is.na(dame_pop)) %>% 
  mutate(dame_pop=str_replace(dame_pop, "X", "x")) %>% 
  mutate(sire_pop=str_replace(sire_pop, "X", "x")) %>% 
  mutate(date_collected=ymd(date_collected), Year_Collected=year(date_collected),
        Year_Collected=ifelse(is.na(Year_Collected), 2023, Year_Collected))
#head(F2s_short)

F2s_short_after_ripened <- F2s_short %>% filter(Year_Collected < 2025)

F2s_plant <- F2s_short_after_ripened %>% 
  group_by(dame_pop, sire_pop) %>% 
  summarise(Unique_Crosses=sum(!is.na(seeds_avail)), Sum_Seeds=sum(seeds_avail)) %>% 
  #mutate(pots_to_plant=ifelse(Sum_Seeds < 16, Sum_Seeds, 16),
     #    seeds_to_plant=ifelse(Sum_Seeds < 48, Sum_Seeds, 48)) %>% 
  arrange(Sum_Seeds) 
#F2s_plant
dim(F2s_plant) #128 types of F2s
sum(F2s_plant$Sum_Seeds) #2941 total seeds available
#sum(F2s_plant$pots_to_plant) 

F2s_short_after_ripened_summarize_WL2 <- F2s_plant %>% 
  mutate(WL2_mom =str_detect(dame_pop, "WL2"), 
         WL2_dad=str_detect(sire_pop, "WL2"), 
         WL2_cross=ifelse(WL2_mom==TRUE | WL2_dad==TRUE, TRUE, FALSE)) %>% 
  mutate(Cross_Type=if_else(sire_pop=="WL2", "BC1", "Other_F2")) %>% 
  filter(WL2_cross == TRUE) %>% 
  filter(Sum_Seeds>0) %>% 
  select(dame_pop:Sum_Seeds, WL2_cross, Cross_Type) %>% 
  arrange(Cross_Type)
head(F2s_short_after_ripened_summarize_WL2)
dim(F2s_short_after_ripened_summarize_WL2) #48 types of F2s with WL2 involved 
F2s_short_after_ripened_summarize_WL2 %>% filter(Cross_Type=="BC1") #11 BC1s with seeds available 
sum(F2s_short_after_ripened_summarize_WL2$Sum_Seeds) #2941 total seeds available

F2s_to_plant_2025 <- F2s_short_after_ripened_summarize_WL2 %>% 
  mutate(BC2_parent=if_else(Cross_Type=="BC1" & str_detect(dame_pop, "TM2") | 
                            Cross_Type=="BC1" & str_detect(dame_pop, "DPR") |
                            Cross_Type=="BC1" & str_detect(dame_pop, "BH" )|
                            Cross_Type=="BC1" & str_detect(dame_pop, "WV" )|
                            Cross_Type=="BC1" & str_detect(dame_pop, "WL1") |
                              Cross_Type=="BC1" & str_detect(sire_pop,"TM2") | 
                              Cross_Type=="BC1" & str_detect(sire_pop,"DPR") |
                              Cross_Type=="BC1" & str_detect(sire_pop,"BH" )|
                              Cross_Type=="BC1" & str_detect(sire_pop,"WV" )|
                              Cross_Type=="BC1" & str_detect(sire_pop,"WL1"), TRUE, FALSE)) %>% 
  filter(BC2_parent==FALSE) %>% 
  mutate(pots_to_plant_raw = if_else(Sum_Seeds<3, Sum_Seeds, Sum_Seeds/3),
         pots_to_plant_round = round(pots_to_plant_raw),
         seeds_to_plant = Sum_Seeds) %>% 
  arrange(seeds_to_plant)
F2s_to_plant_2025
sum(F2s_to_plant_2025$pots_to_plant_round) #357
sum(F2s_to_plant_2025$seeds_to_plant) #1049
summary(F2s_to_plant_2025) #avg pots to plant = 8
```

### Parents
```{r}
parents <- tibble(pop.id=c("LV1", "SQ3", "WL1", "YO11", "BH", "CC", "DPR", "WV", "TM2", "WL2"), 
                  pots_to_plant=c(21, 21, 21, 21, 21, 21, 21, 21, 98, 98),
                  elevation_class=c("High", "High", "High", "High", "Low", "Low", "Low", "Low", "Low", "High")) #these are not neccesarily accurate, just for easy coding 
#parents

parents_labels <- parents %>% slice(rep(1:n(), times = pots_to_plant))
parents_labels_germ <- parents_labels %>% 
  group_by(pop.id) %>% mutate(Rep = row_number()) %>% 
  arrange(elevation_class)
parents_labels_germ
```

## Make a planning sheet

stratification.date, pop.id, rep
```{r}
parents_labels_plan <- parents_labels_germ %>% 
  ungroup() %>% 
  mutate(stratification.date = if_else(elevation_class=="High", "2025-02-27", "2025-03-27")) %>% 
  select(stratification.date, pop.id, Rep)
parents_labels_plan
```

```{r}
F1s_labels <- F1s_to_plant_2025 %>% 
  unite("pop.id", dame_pop:sire_pop, sep=" x ", remove = FALSE) %>% 
  slice(rep(1:n(), times = pots_to_plant_round))

F1s_labels_germ <- F1s_labels %>% 
  group_by(pop.id) %>% mutate(Rep = row_number())
  
F1s_labels_plan <- F1s_labels_germ %>% 
  ungroup() %>% 
  arrange(pots_to_plant_round) %>% 
  mutate(stratification.date="2025-02-27") %>% 
  select(stratification.date, pop.id, Rep)

F1s_labels_plan
```


```{r}
F2s_labels <- F2s_to_plant_2025 %>% 
  mutate(dame_pop = paste0("(", dame_pop, ")"), sire_pop = paste0("(", sire_pop, ")")) %>% 
  unite("pop.id", dame_pop:sire_pop, sep=" x ", remove = FALSE) %>% 
  slice(rep(1:n(), times = pots_to_plant_round))

F2s_labels_germ <- F2s_labels %>% 
  group_by(pop.id) %>% mutate(Rep = row_number())
  
F2s_labels_plan <- F2s_labels_germ %>% 
  ungroup() %>% 
  arrange(pots_to_plant_round) %>% 
  mutate(stratification.date="2025-02-27") %>% 
  select(stratification.date, pop.id, Rep)

F2s_labels_plan
```

```{r}
gs4_create(
  "Summer_25_Planting_Planning",
  sheets = list(Parents=parents_labels_plan,
                F2s=F1s_labels_plan,
                F1s=F2s_labels_plan)
)
#need to add rack #, dame_mf and sire_mf, and unique.ID
```

## Make a planting sheet
pop.id, rep, unique.id, seeds_per_pot, Notes 

```{r}
parents_labels_plant <- parents_labels_germ %>% 
  ungroup() %>% 
  mutate(stratification.date = if_else(elevation_class=="High", "2025-02-27", "2025-03-27"),
         seeds_to_plant=3*pots_to_plant) %>% 
  select(stratification.date, pop.id, Rep, pots_to_plant, seeds_to_plant)
  
F1s_labels_plant <- F1s_labels_germ %>% 
  ungroup() %>% 
  arrange(pots_to_plant_round) %>% 
  mutate(stratification.date="2025-02-27") %>% 
  select(stratification.date, pop.id, Rep, pots_to_plant=pots_to_plant_round, seeds_to_plant)

F2s_labels_plant <- F2s_labels_germ %>% 
  ungroup() %>% 
  arrange(pots_to_plant_round) %>% 
  mutate(stratification.date="2025-02-27") %>% 
  select(stratification.date, pop.id, Rep, pots_to_plant=pots_to_plant_round, seeds_to_plant)
```

```{r}
eight_weeks_strat <- parents_labels_plant %>% 
  filter(stratification.date=="2025-02-27") %>% 
  bind_rows(F1s_labels_plant, F2s_labels_plant)
```

```{r}
four_weeks_strat <- parents_labels_plant %>% 
  filter(stratification.date=="2025-03-27")
```

```{r}
gs4_create(
  "Summer_25_Planting_Sheets",
  sheets = list(eight_weeks_strat=eight_weeks_strat,
                four_weeks_strat=four_weeks_strat)
)
```